package com.example.tms.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateSerializer;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Positive;

import java.time.LocalDate;

public class Transaction {

    // Generated by the service on creation; never supplied by the client.
    @JsonProperty("id")
    private String id;

    // @NotNull catches a missing field; the @JsonFormat + deserializer
    // cause Jackson to reject any value that is not a valid yyyy-MM-dd date
    // with an HttpMessageNotReadableException before Bean Validation even runs.
    @NotNull(message = "Transaction date is required")
    @JsonFormat(pattern = "yyyy-MM-dd")
    @JsonDeserialize(using = LocalDateDeserializer.class)
    @JsonSerialize(using = LocalDateSerializer.class)
    @JsonProperty("transactionDate")
    private LocalDate transactionDate;

    @NotBlank(message = "Account number is required")
    @Pattern(regexp = "\\d{12}", message = "Account number must be exactly 12 digits (numbers only)")
    @JsonProperty("accountNumber")
    private String accountNumber;

    @NotBlank(message = "Account holder name is required")
    @JsonProperty("accountHolderName")
    private String accountHolderName;

    @NotNull(message = "Amount is required")
    @Positive(message = "Amount must be greater than 0")
    @JsonProperty("amount")
    private Double amount;

    @JsonProperty("status")
    private String status;

    // Default constructor (required for JSON deserialization)
    public Transaction() {}

    public Transaction(String id, LocalDate transactionDate, String accountNumber,
                       String accountHolderName, Double amount, String status) {
        this.id = id;
        this.transactionDate = transactionDate;
        this.accountNumber = accountNumber;
        this.accountHolderName = accountHolderName;
        this.amount = amount;
        this.status = status;
    }

    // --- Getters & Setters ---

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public LocalDate getTransactionDate() {
        return transactionDate;
    }

    public void setTransactionDate(LocalDate transactionDate) {
        this.transactionDate = transactionDate;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getAccountHolderName() {
        return accountHolderName;
    }

    public void setAccountHolderName(String accountHolderName) {
        this.accountHolderName = accountHolderName;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
